name: CI/CD on Amazon Linux

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_HOST.REMOTE_USER }}
          key: ${{ secrets.REMOTE_HOST.SSH_PRIVATE_KEY }}
          source: "./"
          target: "/var/www/"

      - name: Run
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_HOST.REMOTE_USER }}
          key: ${{ secrets.REMOTE_HOST.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/
            sudo docker compose down -v
            sudo docker compose up -d
